### ISSUE TITLE
Create the main library into the server service

### ISSUE THREAD

**Issue by dani-vh** [dani-vh/python-react-web-app-template#1]
There should be a library created inside the server, which goal is to include the necessary tools that will access multiple databases and will perform an ETL for each one, everything will be used by a CLI and an API Rest. So, I don't really know how to organize that. There are multiple options that comes to my mind:

1. Create a python package by using [this](https://github.com/kragniz/cookiecutter-pypackage-minimal) template.
2. Just create a folder an put the code in there without necesarily create a python package.
3. Create a python package in a different github repo by using some of the cookiecutter templates and then use it from this project.

Note: the goal of this issue is to just provide a way to go or a template, so that, the rest of the people can continue working on this in a private repo.

Questions:
1. How can we make the code formatting and the auto-completion to work properly in VS since this project is meant to be developed through docker? Is it necessary to manually define a dev-requirements.txt and then a virtual environment for VS to access those features?

**Comment by odarbelaeze** [comment]
Hi Dani,

Addressing your question only:

Let's preface by saying I do prefer local development environments, meaning I get python, node, etc. set up to work directly on my machine instead of a container. That makes setup a tad more complicated, but it facilitates working with any dev tools.

That said, vs code has an extension to work from a remote container, read more [here](https://code.visualstudio.com/docs/remote/containers), it allows you to open your code folder from the container, and all the vs code tooling works from the container itself. You only run the UI from your host machine.

I hope this helps.

**Comment by dani-vh** [comment]
Hey @odarbelaeze, nice, sounds good, thank you. I'll take that in mind, it will be better to just define a local virtual env it seems to be easier for sure.

Do you have any other suggestion to solve that question on how to organize the core code?
